include: package:effective_dart/analysis_options.yaml

analyzer:
  errors:
    todo: ignore
  exclude:
    - "lib\\app\\shared\\locale\\**"
    - "*_test.dart"
linter:
  rules:
    public_member_api_docs: false
    use_setters_to_change_properties: false
    one_member_abstracts: false
    type_annotate_public_apis: false
